import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Sandip',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Puma',
        logo: '/images/p1.jpg',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'Vishal',
      email: 'vishal@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
    products: [
        {
            _id: '1',
            name: 'Imperative Programming',
            category: 'Degree Books',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            publication: 'vipul',
            rating: 4.5,
            numReview: 10,
            description: 'F.Y.B.Sc (IT) Imperative Programming Textbook Mumbai University',
        },
        {
            _id: '2',
            name: 'Communication Skills',
            category: 'Degree Books',
            image: '/images/CSkill.jpg',
            price: 150,
            countInStock: 20,
            publication: 'vipul',
            rating: 3.8,
            numReview: 16,
            description: 'F.Y.B.Sc (IT) Communication Skills Textbook Mumbai University',
        },
        {
            _id: '3',
            name: 'Data Structure',
            category: 'Degree Books',
            image: '/images/DataStructue.jpg',
            price: 200,
            countInStock: 0,
            publication: 'vipul',
            rating: 4.6,
            numReview: 20,
            description: 'S.Y.B.Sc (IT) Data Structure Textbook Mumbai University',
        },
        {
            _id: '4',
            name: 'Digital Electronics',
            category: 'Degree Books',
            image: '/images/DigElectronic.jpg',
            price: 180,
            countInStock: 5,
            publication: 'vipul',
            rating: 4.0,
            numReview: 14,
            description: 'F.Y.B.Sc (IT) Digital Electronics Textbook Mumbai University',
        },
        {
            _id: '5',
            name: 'Discrite Mathematics',
            category: 'Degree Books',
            image: '/images/DiscMath.jpg',
            price: 130,
            countInStock: 11,
            publication: 'vipul',
            rating: 3.2,
            numReview: 10,
            description: 'F.Y.B.Sc (IT) Discrite Mathematics Textbook Mumbai University',
        },
        {
            _id: '6',
            name: 'Object Oriented Programming Language',
            category: 'Degree Books',
            image: '/images/OOPs.jpg',
            price: 170,
            countInStock: 3,
            publication: 'vipul',
            rating: 4.5,
            numReview: 15,
            description: 'F.Y.B.Sc (IT) Object Oriented Programming Language Textbook Mumbai University',
        },
    ],
}
export default data;